version: "3"

networks:
  marvelnetwork:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/app"
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - marvelnetwork
  redis:
    image: redis:4.0
    ports:
      - "6379:6379"
    networks:
      - marvelnetwork