openapi: 3.0.1
info:
  title: Ryan Gunawardana - Marvel API
  description: 'Test exam for integrating with Marvel API'
  contact:
    email: ryanmgunawardana@gmail.com
  version: 1.0.0
externalDocs:
  description: Github Repository
  url: https://github.com/ryanguna/marvel-api
servers:
  - url: http://localhost:3000
tags:
  - name: characters
    description: Everything about Marvel Characters
paths:
  /characters:
    get:
      tags:
        - characters
      summary: Get all characters
      description: Multiple status values can be provided with comma separated strings
      operationId: getCharacters
      parameters:
        - name: limit
          in: query
          description: Limit records
          required: false
          schema:
            type: integer
            default: 100
            minimum: 1
            maximum: 100
        - name: offset
          in: query
          description: Page number
          required: false
          schema:
            type: integer
            default: 0
            minimum: 0
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: integer
                  example: '10002, 10003, 10004'

  /characters/{characterId}:
    get:
      tags:
        - characters
      summary: Find character by ID
      description: Fetches a single character resource
      operationId: getByCharacterId
      parameters:
        - name: characterId
          in: path
          description: ID of character to return
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Character'
        404:
          $ref: '#/components/responses/NotFound'

components:
  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    Character:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1011334
        name:
          type: string
          example: '3-D Man'
        description:
          type: string
          example: 'Kinda cool!'

    Error:
      type: object
      properties:
        status:
          type: integer
        message:
          type: string
        errors:
          type: array
          default: []
      required:
        - status
        - message